name: Build precompiled NIFs

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_nif:
    name: NIF ${{ matrix.nif }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            nif: "2.17"
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
            nif: "2.17"
          - target: x86_64-apple-darwin
            os: macos-13
            nif: "2.17"
          - target: aarch64-apple-darwin
            os: macos-14
            nif: "2.17"

    steps:
      - uses: actions/checkout@v4

      - name: Build precompiled NIF
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: ex_gdal_nif
          project-dir: native/ex_gdal_nif
          project-version: ${{ github.ref_name }}
          target: ${{ matrix.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nif-${{ matrix.target }}-${{ matrix.nif }}
          path: priv/native/*
          if-no-files-found: error

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: priv/native/*
